
CREATE USER user1 WITH PASSWORD 'p1';
CREATE USER user2 WITH PASSWORD 'p2';
\du;

CREATE DATABASE db1;
GRANT ALL PRIVILEGES ON DATABASE db1 TO user1;

REVOKE ALL ON DATABASE db1 FROM PUBLIC;
GRANT CONNECT ON DATABASE db1 to user2;

ALTER USER user1 WITH PASSWORD 'new_p1';
ALTER USER user2 WITH PASSWORD 'new_p2';
\du;
